apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    # enable flagd injection for this workload
    openfeature.dev/enabled: "true"
    # flag source configuration(FeatureFlagSource) crd reference. See end-to-end.yaml for example
    openfeature.dev/featureflagsource: "FeatureFlagSource"
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80